//! NOTE: this file is autogenerated, DO NOT MODIFY
pub const everything = @import("win32/everything.zig");
pub const microsoft = @import("win32/microsoft.zig");
pub const missing = @import("win32/missing.zig");
pub const windowlongptr = @import("win32/windowlongptr.zig");
pub const windows = @import("win32/windows.zig");
pub const zig = @import("win32/zig.zig");
test {
    @import("std").testing.refAllDecls(@This());
}
