//! NOTE: this file is autogenerated, DO NOT MODIFY
pub const internet_explorer = @import("web/internet_explorer.zig");
pub const ms_html = @import("web/ms_html.zig");
test {
    @import("std").testing.refAllDecls(@This());
}
